# Generated by Django 5.2.8 on 2025-12-07 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('additional_name', models.CharField(blank=True, max_length=50)),
                ('headline', models.CharField(blank=True, max_length=100)),
                ('about_me', models.TextField()),
                ('markdown_body', models.TextField()),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Page',
                'verbose_name_plural': 'About Page',
            },
        ),
    ]
