# Generated by Django 5.2.8 on 2025-12-10 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_name', models.CharField(blank=True, max_length=100)),
                ('language', models.CharField(choices=[('es', 'Spanish'), ('en', 'English')], max_length=2)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('headline', models.CharField(blank=True, max_length=100)),
                ('about_me', models.TextField(blank=True)),
                ('markdown_body', models.TextField()),
                ('updated_at', models.DateField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_pages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'About Page',
                'verbose_name_plural': 'About Pages',
                'constraints': [models.UniqueConstraint(fields=('owner', 'language'), name='unique_owner_language')],
            },
        ),
    ]
